sudo: required
language: python
cache: pip
python:
- '3.7'
install:
- pip install mkdocs mkdocs-material pygments mkdocs-img2fig-plugin mkdocs-git-revision-date-localized-plugin
script:
- mkdocs build
after_success:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mkdocs gh-deploy --force; else echo "Pull Request - skipping deployment."; fi"
before_install:
- openssl aes-256-cbc -K $encrypted_e92a2cfd1ea0_key -iv $encrypted_e92a2cfd1ea0_iv
  -in deploy-key-travis.enc -out deploy-key-travis -d
